apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: stroke-servicemonitor
  labels:
    release: kube-prometheus-stack   # Should match the heml chart's release name
spec:
  selector:
    matchLabels:
      app: aks-stroke-app            
  endpoints:
    - port: http                    
      path: /metrics
      interval: 15s